name: bikedna
channels:
  - conda-forge
  - defaults
dependencies:
  - networkx
  - ipykernel
  - momepy
  - folium
  - jupyterlab
  - geopandas
  - osmnx
  - pyyaml
  - contextily
  - pandas
  - matplotlib
  - haversine
  - nbconvert